debug: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kingdee_patchcheck?characterEncoding=utf-8&&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  mvc:
    view:
      prefix: /static/page/
      suffix: .jsp

server:
  port: 9000
  servlet:
    context-path: /patchcheck
ftp:
  host: localhost
  port: 21
  file: F:/patchcheck/
  username: root
  password: root




